import 'dotenv/config';
import http from 'http';
import app from './app.js';
import connectDB from './config/db.js';
import { initSocket } from './config/socket.js';
const PORT = process.env.PORT || 5000;
await connectDB();
const server = http.createServer(app);
initSocket(server);
server.listen(PORT, () => console.log(`HackScore API running on http://localhost:${PORT}`));
